// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReactHooks = require("@apollo/react-hooks");

function mapEmptyObject(data) {
  var match = Caml_obj.caml_equal(data, { });
  if (match) {
    return undefined;
  } else {
    return Caml_option.some(data);
  }
}

function MakeProject(Config) {
  var MakeQuery = function (QueryConfig) {
    var mapOnCompleted = function (oc, jsData) {
      return Curry._1(oc, Curry._1(Config[/* parse */0], jsData));
    };
    var useQuery = function (query, displayName, skip, variables, fetchPolicy, errorPolicy, pollInterval, client, notifyOnNetworkStatusChange, context, partialRefetch, returnPartialData, ssr, onCompleted, onError, param) {
      var tmp = { };
      if (displayName !== undefined) {
        tmp.displayName = Caml_option.valFromOption(displayName);
      }
      if (skip !== undefined) {
        tmp.skip = Caml_option.valFromOption(skip);
      }
      var tmp$1 = Belt_Option.map(variables, QueryConfig[/* parse */0]);
      if (tmp$1 !== undefined) {
        tmp.variables = Caml_option.valFromOption(tmp$1);
      }
      if (fetchPolicy !== undefined) {
        tmp.fetchPolicy = Caml_option.valFromOption(fetchPolicy);
      }
      if (errorPolicy !== undefined) {
        tmp.errorPolicy = Caml_option.valFromOption(errorPolicy);
      }
      if (pollInterval !== undefined) {
        tmp.pollInterval = Caml_option.valFromOption(pollInterval);
      }
      if (client !== undefined) {
        tmp.client = Caml_option.valFromOption(client);
      }
      if (notifyOnNetworkStatusChange !== undefined) {
        tmp.notifyOnNetworkStatusChange = Caml_option.valFromOption(notifyOnNetworkStatusChange);
      }
      if (context !== undefined) {
        tmp.context = Caml_option.valFromOption(context);
      }
      if (partialRefetch !== undefined) {
        tmp.partialRefetch = Caml_option.valFromOption(partialRefetch);
      }
      if (returnPartialData !== undefined) {
        tmp.returnPartialData = Caml_option.valFromOption(returnPartialData);
      }
      if (ssr !== undefined) {
        tmp.ssr = Caml_option.valFromOption(ssr);
      }
      var tmp$2 = Belt_Option.map(onCompleted, mapOnCompleted);
      if (tmp$2 !== undefined) {
        tmp.onCompleted = Caml_option.valFromOption(tmp$2);
      }
      if (onError !== undefined) {
        tmp.onError = Caml_option.valFromOption(onError);
      }
      var opt = tmp;
      var response = ReactHooks.useQuery(query, opt);
      return /* record */[
              /* data */Belt_Option.map(Belt_Option.flatMap(Caml_option.undefined_to_opt(response.data), mapEmptyObject), Config[/* parse */0]),
              /* loading */response.loading,
              /* error */Caml_option.undefined_to_opt(response.error),
              /* variables */Curry._1(QueryConfig[/* parse */0], response.variables),
              /* networkStatus */response.networkStatus
            ];
    };
    return /* module */[
            /* mapOnCompleted */mapOnCompleted,
            /* useQuery */useQuery
          ];
  };
  return /* module */[/* MakeQuery */MakeQuery];
}

exports.mapEmptyObject = mapEmptyObject;
exports.MakeProject = MakeProject;
/* @apollo/react-hooks Not a pure module */
